ux_icons:
  aliases:
    show: bx:show
    code: tabler:api
    external: tabler:external-link
    search: tabler:search
    inst: material-symbols:museum-outline
    obj: material-symbols:wall-art-outline-rounded
    facebook: tabler:brand-facebook
    'layout-grid': tabler:list

  default_icon_attributes:

    # Use current text color to fill the icon
    fill: currentColor

    # Default dimensions
    height: '1em'
    width: '1em'

        #    fill:                currentColor

      # Example:
      # class:               icon

    # Icon sets configuration.
  icon_sets:

      # Prototype: the icon set prefix (e.g. "acme")
      prefix:

        # The local icon set directory path.
        # (cannot be used with 'alias')
        path:                 ~ # Example: '%kernel.project_dir%/assets/svg/acme'

        # The remote icon set identifier.
        # (cannot be used with 'path')
        alias:                ~ # Example: simple-icons

        # Override default icon attributes for icons in this set.
        icon_attributes:      []

          # Examples:
          # class:               'icon icon-acme'
        # fill:                none


      # Examples:
      # dots:                'clarity:ellipsis-horizontal-line'
    # privacy:             'bi:cookie'

    # Configuration for the remote icon service.
  iconify:
      enabled:              true

      # Whether to download icons "on demand".
      on_demand:            false

      # The endpoint for the Iconify icons API.
      endpoint:             'https://api.iconify.design'

    # Ignore error when an icon is not found.
    # Set to 'true' to fail silently.
  ignore_not_found:     true


when@prod:
    ux_icons:
        # Suppress exceptions for missing icons in production
        ignore_not_found: true
